### ISSUE TITLE
Fix remaining module-level imports

### ISSUE THREAD

**Issue by aaaaalbert** [SensibilityTestbed/sensorlib#2]
In 7570416b2b06b8d851346d65a24665c75dedcdcc the example code switched from using `dy_import_module_symbols` to use `dy_import_module`. Unfortunately, a few places are still missing the module name before calls to `request_data`:
- accelerometer.r2py
- light.r2py
- magnetometer.r2py

**Comment by yyzhuang** [comment]
Ok will fix.
